# Organization running event:
organization: 'Open Source Bridge Portland'

# Breadcrumbs that are always visible, each breadcrumb is a name and URI:
breadcrumbs:
  - ['BridgePDX', 'http://www.bridgepdx.com/']

# Timezone for dates in this application:
timezone: 'Pacific Time (US & Canada)'

# Can people create proposals without logging in?
have_anonymous_proposals: false

# Do proposals have excerpts?
have_proposal_excerpts: true

# Do events have tracks?
have_event_tracks: true

# Are proposals associated with multiple presenters?
have_multiple_presenters: true

# Can people upload pictures of themselves?
have_user_pictures: true

# Is profile information, like biography, stored in the User record? Else stored in Proposal.
have_user_profiles: true
