# Public URL of website:
public_url: 'http://opensourcebridge.org/'

# Organization running event:
organization: 'Open Source Bridge'

# Abbreviated name for use in URLs and proposal slugs.
organization_slug: 'osb'

# Top-level tagline or description.
tagline: 'An open source conference in Portland, Oregon | June 2009'

# Breadcrumbs that are always visible, each breadcrumb is a name and URI:
breadcrumbs: []

# Timezone for dates in this application:
timezone: 'Pacific Time (US & Canada)'

# Can people create proposals without logging in?
have_anonymous_proposals: false

# Do proposals have excerpts?
have_proposal_excerpts: true

# Do events have tracks?
have_event_tracks: true

# Do events have session types?
have_event_session_types: true

# Display events picker?
have_events_picker: false

# Are proposals associated with multiple presenters?
have_multiple_presenters: true

# Can people upload pictures of themselves?
have_user_pictures: true

# Is profile information, like biography, stored in the User record? Else stored in Proposal.
have_user_profiles: true
