# Organization running event:
organization: 'Open Source Bridge Portland'

# Breadcrumbs that are always visible, each breadcrumb is a name and URI:
breadcrumbs:
  - ['BridgePDX', 'http://www.bridgepdx.com/']

# Timezone for dates in this application:
timezone: 'Pacific Time (US & Canada)'

# Do users have profiles? If true, bio is part of the User; else part of the Proposal.
has_profiles: true
